### PR TITLE
Fix for 0655 Skylake architecture for Chameleon. Needs some more testing. 

### PR DESCRIPTION
**Pull request by tpatki**

### CODE REVIEW

**Comment by slabasan** [comment]
@tpatki Can you update the README to reflect experimental Skylake support as part of your PR as well?

**Comment by tpatki** [comment]
@slabasan: Added. Thanks!

**Comment by tpatki** [comment]
@srini009 has confirmed that this works correctly for power capping on the skylake nodes on Chameleon, just FYI.

**Comment by srini009** [comment]
I am testing out the msrmod tool on skylake, and there a couple of issues:
1. When setting the package and dram power caps like so: ./msrmod -c 1 -s memory -a 35 -b 2 -e 25 -f 4, 
libmsr applies the same power cap to both sockets, even though I want this power cap applied to socket ID 1. Essentially, the "c" flag doesn't seem to have any effect here.
2. Before setting any power cap,s when reading the existing power caps on the package and domains, I see an error message probably related to some junk/invalid msr register values:
Command: ./msrmod -p rapl -t 0
Output message: 
=== Pkg Domain ===
- Socket 0 Limit 0 -
bits    = 982d000178320
seconds = 2.000000
watts   = 100.000000
- Socket 0 Limit 1 -
bits    = 982d000178320
seconds = 4.000000
watts   = 90.000000
- Socket 1 Limit 0 -
bits    = 982d000178320
seconds = 2.000000
watts   = 100.000000
- Socket 1 Limit 1 -
bits    = 982d000178320
seconds = 4.000000
watts   = 90.000000

=== DRAM Domain ===
- Socket 0 -
Error: <libmsr> Invalid bit field values: calc_rapl_bits(): Seconds value is too large: srini-testing.novalocal:/home/cc/libmsr/src/msr_rapl.c::442
bits    = 0
seconds = 0.000000
watts   = 0.000000
- Socket 1 -
Error: <libmsr> Invalid bit field values: calc_rapl_bits(): Seconds value is too large: srini-testing.novalocal:/home/cc/libmsr/src/msr_rapl.c::442
bits    = 0
seconds = 0.000000
watts   = 0.000000

**Comment by srini009** [comment]
However, the power caps seem to be applied successfully, though.

**Comment by slabasan** [comment]
Hi @srini009, thanks for testing this and providing feedback! 
1) I can't seem to replicate this one on catalyst. When I run `./msrmod -c 1 -s memory -a 35 -b 2 -e 25 -f 4`, I see that it only sets socket 1 (initially printing out the RAPL information with `-p rapl`, both sockets have a 0W power limit):
```
=== DRAM Domain ===
- Socket 0 -
Error: <libmsr> Invalid bit field values: calc_rapl_bits(): Seconds value is too large: catalyst160:/g/g19/labasan1/git_root_pub/libmsr_public/src/msr_rapl.c::439
bits    = 0
seconds = 0.000000
watts   = 0.000000
- Socket 1 -
bits    = 168118
seconds = 2.000000
watts   = 35.000000
```

I think we also need to print an error or warning that when setting the DRAM power limit, only power limit and time window 1 (`-a` and `-b`) are accepted.

Similarly, setting the package-level power limit on socket 1 also works for me `./msrmod -c 0 -s package -a 100 -b 2`:
```
=== Pkg Domain ===
- Socket 0 Limit 0 -
bits    = 1800000178320
seconds = 2.000000
watts   = 100.000000
- Socket 0 Limit 1 -
bits    = 1800000178320
seconds = 0.000000
watts   = 0.000000
- Socket 1 Limit 0 -
bits    = 6845000148398
seconds = 1.000000
watts   = 115.000000
- Socket 1 Limit 1 -
bits    = 6845000148398
seconds = 3.000000
watts   = 138.000000
```

2) The following error arises because of the time window: `Error: Invalid bit field values: calc_rapl_bits(): Seconds value is too large: srini-testing.novalocal:/home/cc/libmsr/src/msr_rapl.c::442`. Perhaps we should change the wording to a warning, since it does not affect setting the power limit.

**Comment by srini009** [comment]
Hi Stephanie,
That's right - the second error is likely just a warning. It doesn't really affect anything. 
Also, I am running on a Skylake CPU from Chameleon: https://chi.tacc.chameleoncloud.org
CPU details from cat /proc/cpuinfo: 
Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz

**Comment by slabasan** [comment]
Should the platform matter in debugging the behavior of item 1? I would think the msrmod APIs would behave the same on Skylake and Ivy Bridge.

**Comment by srini009** [comment]
@slabasan: I am not sure why different platforms show different behavior for the msrmod API, but I can definitely see this issue on Skylake processors available through the chameleon cloud service. 

Another thing I notice while using the dump_rapl_data() function programmatically - libmsr correctly detects the number of sockets, but somehow I am getting the same current power usage readings on both sockets for the package and DRAM domains (using struct rapl_data rd->pkg_watts and rd->dram_watts).
i.e, package_power[socket0] = package_power[socket1] && dram_power[socket0] = dram_power[socket1]. 

Should we expect to get the EXACT same power usage all the time on both sockets? I would think not, right? Any idea what is going on/what I am doing incorrectly? Even the libmsr_test app shows the same behavior. 

Regards,
Srini

**Comment by srini009** [comment]
Hi @slabasan, @tpatki 
I was wondering about your experiences with DRAM capping on Skylake nodes (or any other architecture as well) - have you seen any case where DRAM power capping through libmsr+RAPL does not seem to have any effect on the DRAM power usage? In other words, the libmsr API works without returning any error messages, but DRAM power capping hasn't taken any effect.

Attached is an example of such a scenario on a Skylake node from Chameleon:
dram_capping_not_working

**Comment by slabasan** [comment]
Can you run the power rapl test in the `tests/` directory? It should set both the PKG and DRAM power limits, then read them back. Are you sure the register is accepting the value? Is your value within the expected min/max for the DRAM domain? I am a bit confused by your graph -- what is the lower limit of 27W for the DRAM? I thought the DRAM domain only had 1 power limit.

**Comment by srini009** [comment]
Hi Stephanie,

I cannot find the power_capl test - these are the available tests under the test/ directory in the patki-skylake-0655-fix branch:
[cc@srini-testing test]$ pwd
/home/cc/LIBMSR/test
[cc@srini-testing test]$ ls
CMakeFiles           libmsr_dump_data  Makefile        power_unit_test  read_rapl_data            turbo_test
cmake_install.cmake  libmsr_test       power_cap_test  pstate_test      translate_pkg_rapl_limit

I believe you are referring to the power_cap_test? I ran that test, and it was able to set the power limits successfully - there didn't seem to be any errors from running that test.

I apologize for the confusing definition in the plot above - the 27W lower limit is the "minimum allowed" value for the DRAM - this is a rapl-defined hardware limit. I am setting the power cap to 30 W - you are right, there is only 1 power limit for the DRAM.

Also, I tried setting the DRAM cap through MSRMOD, and I see the same behavior - the cap appears to be set properly, but the application DRAM power usage clearly violates the cap. 

Regards,
Srinivasan Ramesh

**Comment by slabasan** [comment]
So the minimum allowed power cap for DRAM is 27W, you set it to 30W, but you are seeing it consume 75W? Can you send the output of running `power_cap_test` and doing a `./rdmsr 0x618` (MSR_DRAM_POWER_LIMIT)? Is bit 32 a value of 1?

**Comment by srini009** [comment]
Hi Stephanie,
Yep, that is correct - the cap is set to 30W, but application consumes 75W (I have tried various window sizes, nothing seems to work)
I am unable to find the "rdmsr" binary anywhere - where can I find this inside libmsr? 

Regards,
Srinivasan Ramesh

**Comment by srini009** [comment]
Ah hold on - I can use msrmod to read the MSR register.
Here is the output for ./test/power_cap_test:

===== MSR Init Done =====

===== RAPL Init Done =====

===== Get Initial RAPL Power Limits =====
Socket 0:
Pkg Domain Power Lim 1 (lower lim)
bits    = 184b0001183e8
seconds = 0.250000
watts   = 125.000000

Pkg Domain Power Lim 2 (upper lim)
bits    = 184b0001183e8
seconds = 0.000000
watts   = 150.000000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

Socket 1:
Pkg Domain Power Lim 1 (lower lim)
bits    = 184b0001183e8
seconds = 0.250000
watts   = 125.000000

Pkg Domain Power Lim 2 (upper lim)
bits    = 184b0001183e8
seconds = 0.000000
watts   = 150.000000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

===== Start Socket 0 RAPL Power Limit Test =====

--- Testing Pkg Domain Lower Limit ---
Setting socket 0 PL1 to 87.5W (70%)
Socket 0:
Pkg Domain Power Lim 1 (lower lim)
bits    = 184b0001582bc
seconds = 1.000000
watts   = 87.500000

Pkg Domain Power Lim 2 (upper lim)
bits    = 184b0001582bc
seconds = 0.000000
watts   = 150.000000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

Socket 1:
Pkg Domain Power Lim 1 (lower lim)
bits    = 184b0001582bc
seconds = 1.000000
watts   = 87.500000

Pkg Domain Power Lim 2 (upper lim)
bits    = 184b0001582bc
seconds = 0.000000
watts   = 150.000000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

--- Testing Pkg Domain Upper Limit ---
Setting socket 0 PL2 to 112.5W (90%)
Socket 0:
Pkg Domain Power Lim 1 (lower lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 87.500000

Pkg Domain Power Lim 2 (upper lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 112.500000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

Socket 1:
Pkg Domain Power Lim 1 (lower lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 87.500000

Pkg Domain Power Lim 2 (upper lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 112.500000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

===== End Socket 0 RAPL Power Limit Test =====

===== Start Socket 1 RAPL Power Limit Test =====

--- Testing Pkg Domain Lower Limit ---
Setting socket 1 PL1 to 87.5W (70%)
Socket 0:
Pkg Domain Power Lim 1 (lower lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 87.500000

Pkg Domain Power Lim 2 (upper lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 112.500000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

Socket 1:
Pkg Domain Power Lim 1 (lower lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 87.500000

Pkg Domain Power Lim 2 (upper lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 112.500000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

--- Testing Pkg Domain Upper Limit ---
Setting socket 1 PL2 to 112.5W (90%)
Socket 0:
Pkg Domain Power Lim 1 (lower lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 87.500000

Pkg Domain Power Lim 2 (upper lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 112.500000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

Socket 1:
Pkg Domain Power Lim 1 (lower lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 87.500000

Pkg Domain Power Lim 2 (upper lim)
bits    = 38384001582bc
seconds = 1.000000
watts   = 112.500000

DRAM Domain
bits    = 108444
seconds = 0.250000
watts   = 136.500000

===== End Socket 1 RAPL Power Limit Test =====

===== Testing All RAPL Power Limits All Sockets =====
Applying 80% power cap to socket 0 --- PL1 = 100.0W, PL2 = 211.2W, DRAM = 109.2W.
Applying 80% power cap to socket 1 --- PL1 = 100.0W, PL2 = 211.2W, DRAM = 109.2W.
Socket 0:
Pkg Domain Power Lim 1 (lower lim)
bits    = 7869900158320
seconds = 1.000000
watts   = 100.000000

Pkg Domain Power Lim 2 (upper lim)
bits    = 7869900158320
seconds = 3.000000
watts   = 211.125000

DRAM Domain
bits    = 148369
seconds = 1.000000
watts   = 109.125000

Socket 1:
Pkg Domain Power Lim 1 (lower lim)
bits    = 7869900158320
seconds = 1.000000
watts   = 100.000000

Pkg Domain Power Lim 2 (upper lim)
bits    = 7869900158320
seconds = 3.000000
watts   = 211.125000

DRAM Domain
bits    = 148369
seconds = 1.000000
watts   = 109.125000
===== End Testing All RAPL Power Limits All Sockets =====

===== Setting Defaults =====
Socket 0:
Pkg Domain Power Lim 1 (lower lim)
bits    = 0
seconds = 1.000000
watts   = 125.000000

Pkg Domain Power Lim 2 (upper lim)
bits    = 0
seconds = 3.000000
watts   = 150.000000

DRAM Domain
bits    = 0
seconds = 1.000000
watts   = 136.500000

Socket 1:
Pkg Domain Power Lim 1 (lower lim)
bits    = 0
seconds = 1.000000
watts   = 125.000000

Pkg Domain Power Lim 2 (upper lim)
bits    = 0
seconds = 3.000000
watts   = 150.000000

DRAM Domain
bits    = 0
seconds = 1.000000
watts   = 136.500000
===== MSR Finalized =====

===== Test Finished Successfully =====




**********************************************************************************************
And here is the output for ./bin/msrmod -p rapl -r 0x618

- Socket 0 Limit 0 -
bits    = 784b0001583e8
seconds = 1.000000
watts   = 125.000000
- Socket 0 Limit 1 -
bits    = 784b0001583e8
seconds = 3.000000
watts   = 150.000000
- Socket 1 Limit 0 -
bits    = 784b0001583e8
seconds = 1.000000
watts   = 125.000000
- Socket 1 Limit 1 -
bits    = 784b0001583e8
seconds = 3.000000
watts   = 150.000000

=== DRAM Domain ===
- Socket 0 -
bits    = 148444
seconds = 1.000000
watts   = 136.500000
- Socket 1 -
bits    = 148444
seconds = 1.000000
watts   = 136.500000
Reading MSR 0x618 on CPU 0: 148444

**Comment by srini009** [comment]
Hi Stephanie,
Thank you for the reply - I haven't really experimented with setting a very high value for DRAM - I think 136.5 watts is oddly high (even higher than the default value of ~120W or so for the package!). 
I am actually interested in studying the effect of DRAM power capping on application performance at some stage - perhaps I need to find different hardware to run my experiments, but I am limited to Skylake for the time being.
Also, I just wanted to mention that the patch (fix_hyperthreads) for duplicated power readings on both sockets did not work on Skylake. I applied the patch and still get the exact same values on both sockets most of the time, although "occasionally", I get different values. I am not sure what is going on here. 

Regards,
Srinivasan Ramesh

Regards,
Srinivasan Ramesh

**Comment by tpatki** [comment]
@srini009: Which benchmark are you running when you're observing 75W of DRAM consumption? I'm trying to reproduce your setup on skylake now.

**Comment by srini009** [comment]
Hi Tapasya,
I installed the AMG benchmark (iterative solver that uses HYPRE) (code from here: hhttps://asc.llnl.gov/CORAL-benchmarks/#amg2013), and I am running the GMRES + diagonal preconditioning solver (solver ID 3)
I am using pure MPI on a single Skylake node (MPICH 3.2) with socket binding to prevent performance variation. This Skylake node has 2 sockets, with 12 cores per socket, and 2 threads per core (hyperthreading is enabled I believe)
cd test/ and use this run command: mpiexec -n 24 -bind-to socket:1 ./amg2013 -pooldist 1 -r 48 48 48 -P 3 1 1 -solver 3

Regards,
Srinivasan Ramesh

**Comment by tpatki** [comment]
Do you have an existing snapshot I can use on chameleon?

**Comment by tpatki** [comment]
@srini009: I'm unable to get your snapshot up and running (I've encountered this before, so not sure if it's the same issue). I have a new lease on chameleon, and I'm trying to launch an instance and specify your image as the source file. I get an error on the lines of "No valid host was found. There are not enough hosts available." when I already have an allocation. 

Any idea what causes this? Anything to do with the fact that the visibility for your snapshot is private and not public? 
screen shot 2018-08-17 at 10 48 57 am

**Comment by tpatki** [comment]
@srini009:
Probably has nothing to do with your snapshot.  I am getting the same error when I use the GUI to create a baremetal Centos7 instance, or when I use Swann's infrastructure scripts to create a stack. Looks like a different issue with Chameleon. Can you check with Swann if he's seen this before?

**Comment by srini009** [comment]
Hi Tapasya,
The snapshot image is shared, so I believe there should not be any permissions issues. Sure, I shall check with him. I have never actually used his scripts - I just use the GUI directly to create a bare-metal instance and deploy this image. I have never seen this issue personally before. 

Regards,
Srinivasan Ramesh

**Comment by slabasan** [comment]
@srini009: @tpatki  and I debugged the duplicate entries you were seeing on this system (with and without the patch). The layout of physical threads and hyperthreads is not currently handled in the patch, leading to duplicate values. We filed an issue here if you would like to track or have suggestions on how to modify our source to encompass this layout: #30.

**Comment by tpatki** [comment]
Just some notes about chameleon: 

-- There are times when we get a broken lease. Sometimes the nodes are just bad, and the chameleon staff doesn't know about it yet. This results in the issue we saw above. The solution is to create a new lease, delete the old lease, and do it in that order because hardware is allocated at lease creation and we don't want to get the same node again. This hack worked for us.

**Comment by tpatki** [comment]
@srini009, @slabasan: I'm trying to remember where we were on this fix. Should I be rebasing this and testing this on the skylake nodes on chameleon?

**Comment by slabasan** [comment]
@tpatki: You need to rebase your local branch against the tip of master. We merged in a fix for the interleaving issue that was causing duplicate reads on dual-socket systems. The actual commit is `33588fd`. There have been a couple additional fixes on top of that that you will want as well. If you could test this on the Skylake system (assuming the mapping is still the same) and let us know if that resolves the issue.

**Comment by slabasan** [comment]
@tpatki: I have an updated version of your patki-skylake-0655-fix` branch on my fork here: https://github.com/slabasan/libmsr/tree/patki-skylake-0655-fix

Please use this when you test on the Skylake system. The version of this branch will be up-to-date with the `master` branch and will also have the change to the DRAM energy units.

**Comment by tpatki** [comment]
Thanks @slabasan for rebasing and adding the DRAM fix! I'll get around to testing this on chameleon skylake nodes as soon as I can.

**Comment by slabasan** [comment]
Going to close this PR, which added support for Skylake and identified a bug in libmsr's node mapping topology (merged in `c0b09b`). The latter fixes duplicate readings of MSRs on dual-socket systems. The examples pass on Chameleon Skylake nodes. Please feel free to open a new issue if you run into this issue again.

**Pull request closed without merging**
